name: Radio Globe Workflow Test

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hola
        run: echo "Bla bla bla"
        shell: bash
